owner: nxvvvv
repo: status
user-agent: nxvvvv
sites:
  - name: Personal Website
    url: https://navaneethkm.me
  - name: Cooker OS
    url: https://cooker.navaneethkm.me
  - name: Status #heh :D
    url: https://status.navaneethkm.me
status-website:
  customHeadHtml: "<!-- Custom HTML to add in the <head> tag -->"
  customBodyHtml: " |
    <!-- Custom HTML to add at the beginning of <body> -->
    <script>
      // Wait for the DOM to be ready
      document.addEventListener("DOMContentLoaded", function() {
        // Find the footer element by class name
        var footer = document.querySelector(".svelte-jbr799");

        // Check if the footer element exists before making changes
        if (footer) {
          // Create a new paragraph element
          var newParagraph = document.createElement("p");

          // Set the inner HTML of the new paragraph element
          newParagraph.innerHTML = "Custom content goes here. ";

          // Create a link element
          var link = document.createElement("a");

          // Set the attributes of the link (href and text content)
          link.href = "https://example.com";
          link.textContent = "Custom Link";

          // Append the link to the new paragraph
          newParagraph.appendChild(link);

          // Append the new paragraph to the footer
          footer.appendChild(newParagraph);
        }
      });
    </script>"
  cname: status.navaneethkm.me
  name: Status
  theme: night
  faviconSvg: https://github.com/nxvvvv/status/raw/master/assets/upptime-icon.svg
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/nxvvvv
    - title: Website
      href: https://navaneethkm.me
  introTitle: "nxvvvv's Status Page"
  introMessage: This is my Status Page which shows all the online web services made by me, powered by GitHub Actions 🔥
commitMessages:
  commitAuthorName: "nxvvvv"
  commitAuthorEmail: "sudo@member.fsf.org"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
