owner: nxvvvv
repo: status
user-agent: nxvvvv
sites:
  - name: Personal Website
    url: https://navaneethkm.me
  - name: Cooker OS
    url: https://cooker.navaneethkm.me
  - name: Status #heh :D
    url: https://status.navaneethkm.me
status-website:
  cname: status.navaneethkm.me
  name: Status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/nxvvvv
    - title: Website
      href: https://navaneethkm.me
  introTitle: "nxvvvv's Status Page"
  introMessage: This is my Status Page which shows all the online web services made by me, powered by GitHub Actions 🔥
commitMessages:
  commitAuthorName: "nxvvvv"
  commitAuthorEmail: "sudo@member.fsf.org"
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
